---
title: "Video Game Sales Analysis"
author: "Deepak"
date: "2024-04-09"
output: html_document
---

# Setting up environment

```{r echo=TRUE, warning=FALSE}
install.packages("tidyverse")
install.packages("skimr")
install.packages("dplyr")
install.packages("rmarkdown")
install.packages("knitr")
library(tidyverse)
library(readr)
library(skimr)
library(ggplot2)
library(dplyr)
library(rmarkdown)
library(knitr)
```

# Assigning csv file to a dataframe

```{r}
vgsales <- read_csv("vgsales.csv")
```

# Calculating total global sales across years and assigning it to a dataframe

```{r,out.width='1600px',out.height='400'}
yearly_growth <- vgsales %>% 
  group_by(Year) %>% 
  summarise(Total_Global_Sales = sum(Global_Sales)) %>% 
  drop_na()
```

# Total global sales trend acoss years
```{r,out.width='1600px'}
ggplot(data = yearly_growth,mapping = aes(x = Year,y=Total_Global_Sales))+geom_point()+theme(axis.text.x = element_text(angle = 90))
```
# Total sales trend across different regions

## NA region

```{r, out.width='1800px',out.height='450'}
region_trend_NA <- vgsales %>% 
  group_by(Year) %>% 
  summarise(Total_NA_Sales = sum(NA_Sales)) %>% 
  drop_na()

ggplot(data = region_trend_NA,mapping = aes(x = Year,y=Total_NA_Sales))+geom_point()+ theme(axis.text.x = element_text(angle = 90))
```

## EU region

```{r, out.width='1800px',out.height='450'}
region_trend_EU <- vgsales %>% 
  group_by(Year) %>% 
  summarise(Total_EU_Sales = sum(EU_Sales)) %>% 
  drop_na()

ggplot(data = region_trend_EU,mapping = aes(x = Year,y=Total_EU_Sales))+geom_point()+ theme(axis.text.x = element_text(angle = 90))
```

## JP region

```{r, out.width='1800px',out.height='450'}
region_trend_JP <- vgsales %>% 
  group_by(Year) %>% 
  summarise(Total_JP_Sales = sum(JP_Sales)) %>% 
  drop_na()

ggplot(data = region_trend_JP,mapping = aes(x = Year,y=Total_JP_Sales))+geom_point()+ theme(axis.text.x = element_text(angle = 90))
```

# Publisher wise sales

Max sales = Nintendo Falcom Corporation
```{r}
brand_sales <- vgsales %>% 
  group_by(Publisher) %>% 
  summarise(Total_Sales = sum(Global_Sales)) %>% 
  drop_na()
```

# Genre wise sales

```{r,out.width='1800px',out.height='450'}
Genre_sales <- vgsales %>% 
  group_by(Genre) %>% 
  summarise(Total_Sales = sum(Global_Sales)) %>% 
  drop_na()

ggplot(data = Genre_sales, aes(x = Genre, y = Total_Sales)) +
  geom_bar(stat = "identity") +
  labs(x = "Genre", y = "Total Sales", title = "Total Genre Sales")
```